include("common:contract-random-messenger")
include("common:contract-broadcast-random-name")
include("common:contract-deathstar")
include("common:contract-user-provider")
include("common:utils")
include("common:koin")
include("common:compose")
include("common:core")

include("common:test")
